export const register = async (req, res)=>{
    try {
        console.log("clicked register")
    } catch (error) {
        console.log("Error at authController", error)
    }
}

export const login = async (req, res)=>{
    try {
        console.log("clicked login")
    } catch (error) {
        console.log("Error at authController", error)
    }
}